language: php
php: ["7.0"]
sudo: false
install:
- echo | pecl install yaml
- echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- cd ..
- mkdir pm
- cd pm
- wget -O - get.pocketmine.net | bash -s - -v development
- mkdir plugins

before_script:
- cd $TRAVIS_BUILD_DIR
- php compile.php
- cp compile/HereAuth_Dev.phar ../pm/plugins

script:
- cd ../pm
- ./start.sh
